export const COUNTRY_CODE = "PL";

export enum HOLIDAY_TYPES {
  NATIONAL_HOLIDAY = "NATIONAL_HOLIDAY",
  OBSERVANCE = "OBSERVANCE",
  SEASON = "SEASON",
}

export interface HolidayInfo {
  country: string;
  iso: string;
  year: number;
  date: string;
  day: string;
  name: string;
  type: string;
}

export const holidaysExampleResponse = [
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-05-02",
    day: "Tuesday",
    name: "Day of the Flag",
    type: "OBSERVANCE",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-12-22",
    day: "Friday",
    name: "December Solstice",
    type: "SEASON",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-08-15",
    day: "Tuesday",
    name: "Assumption of Mary",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-04-08",
    day: "Saturday",
    name: "Holy Saturday",
    type: "OBSERVANCE",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-04-09",
    day: "Sunday",
    name: "Easter Sunday",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-05-01",
    day: "Monday",
    name: "Labor Day / May Day",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-11-01",
    day: "Wednesday",
    name: "All Saints' Day",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-02-14",
    day: "Tuesday",
    name: "Valentine's Day",
    type: "OBSERVANCE",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-12-31",
    day: "Sunday",
    name: "New Year's Eve",
    type: "OBSERVANCE",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-05-26",
    day: "Friday",
    name: "Mother's Day",
    type: "OBSERVANCE",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-04-07",
    day: "Friday",
    name: "Good Friday",
    type: "OBSERVANCE",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-04-10",
    day: "Monday",
    name: "Easter Monday",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-06-08",
    day: "Thursday",
    name: "Corpus Christi",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-03-20",
    day: "Monday",
    name: "March Equinox",
    type: "SEASON",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-01-06",
    day: "Friday",
    name: "Epiphany",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-12-26",
    day: "Tuesday",
    name: "Second Day of Christmas",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-11-11",
    day: "Saturday",
    name: "Independence Day",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-09-23",
    day: "Saturday",
    name: "September Equinox",
    type: "SEASON",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-12-24",
    day: "Sunday",
    name: "Christmas Eve",
    type: "OBSERVANCE",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-05-28",
    day: "Sunday",
    name: "Whit Sunday",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-01-01",
    day: "Sunday",
    name: "New Year's Day",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-06-23",
    day: "Friday",
    name: "Father's Day",
    type: "OBSERVANCE",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-12-25",
    day: "Monday",
    name: "Christmas Day",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-06-21",
    day: "Wednesday",
    name: "June Solstice",
    type: "SEASON",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-05-03",
    day: "Wednesday",
    name: "Constitution Day",
    type: "NATIONAL_HOLIDAY",
  },
];
