export const holidaysExampleResponse = [
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-08-15",
    day: "Tuesday",
    name: "Assumption of Mary",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-04-09",
    day: "Sunday",
    name: "Easter Sunday",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-05-01",
    day: "Monday",
    name: "Labor Day / May Day",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-11-01",
    day: "Wednesday",
    name: "All Saints' Day",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-04-10",
    day: "Monday",
    name: "Easter Monday",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-06-08",
    day: "Thursday",
    name: "Corpus Christi",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-01-06",
    day: "Friday",
    name: "Epiphany",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-12-26",
    day: "Tuesday",
    name: "Second Day of Christmas",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-11-11",
    day: "Saturday",
    name: "Independence Day",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-05-28",
    day: "Sunday",
    name: "Whit Sunday",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-01-01",
    day: "Sunday",
    name: "New Year's Day",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-12-25",
    day: "Monday",
    name: "Christmas Day",
    type: "NATIONAL_HOLIDAY",
  },
  {
    country: "Poland",
    iso: "PL",
    year: 2023,
    date: "2023-05-03",
    day: "Wednesday",
    name: "Constitution Day",
    type: "NATIONAL_HOLIDAY",
  },
];
